"""Add BlogPost model

Revision ID: 488a558e9c15
Revises: f9ecb6cd8ece
Create Date: 2025-04-20 03:10:05.148991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488a558e9c15'
down_revision = 'f9ecb6cd8ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=150), nullable=False),
    sa.Column('date_posted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_post')
    # ### end Alembic commands ###
