"""added contactMessage model

Revision ID: 54067a7aaa6a
Revises: f0a7afd0d7d6
Create Date: 2025-05-05 00:14:18.237519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54067a7aaa6a'
down_revision = 'f0a7afd0d7d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('date_posted')

    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=45),
               existing_nullable=False)
        batch_op.alter_column('session_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.drop_constraint('uq_visitor_session_id', type_='unique')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.create_unique_constraint('uq_visitor_session_id', ['session_id'])
        batch_op.alter_column('session_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', sa.DATETIME(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.drop_column('date')

    # ### end Alembic commands ###
