"""added is_admin to User model

Revision ID: 782475fcc0fa
Revises: a3f4879ea46f
Create Date: 2025-04-28 20:51:40.068151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782475fcc0fa'
down_revision = 'a3f4879ea46f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitor')
    # ### end Alembic commands ###
