"""Add is_guest to Visitor model

Revision ID: 853ba7d8d5bf
Revises: be4483da628f
Create Date: 2025-04-29 05:36:14.266797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853ba7d8d5bf'
down_revision = 'be4483da628f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_guest')

    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_guest', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_column('is_guest')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_guest', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
