"""Update BlogPost model with named constraints

Revision ID: a3f4879ea46f
Revises: 488a558e9c15
Create Date: 2025-04-26 19:15:34.718785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f4879ea46f'
down_revision = '488a558e9c15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_blogpost_user_id', 'user', ['author'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_blogpost_user_id', type_='foreignkey')
        batch_op.alter_column('author',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###
