"""Add session_id to Visitor model

Revision ID: be4483da628f
Revises: bf2c53786f7c
Create Date: 2025-04-29 05:23:26.345019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4483da628f'
down_revision = 'bf2c53786f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint('uq_visitor_session_id', ['session_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
