"""add is_guest to user model

Revision ID: f0a7afd0d7d6
Revises: 853ba7d8d5bf
Create Date: 2025-04-29 22:02:28.605748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a7afd0d7d6'
down_revision = '853ba7d8d5bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_guest', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_guest')

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
